services:
  # VPN Container
  gluetun:
    image: qmcgaw/gluetun:v3.40
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - 58846:58846 # deluge daemon
      - 8888:8888/tcp # privoxy
    environment:
      - HTTPPROXY=on
      - VPN_SERVICE_PROVIDER=protonvpn
      - VPN_TYPE=wireguard
      - WIREGUARD_PRIVATE_KEY=${WIREGUARD_PRIVATE_KEY}
      - VPN_PORT_FORWARDING=on
      - SERVER_COUNTRIES=Sweden
  # Torrent Client
  deluge:
    image: linuxserver/deluge:2.2.0
    restart: unless-stopped
    network_mode: service:gluetun
    depends_on:
      - gluetun
    volumes:
      - ${DELUGE_DOWNLOAD_LOCATION}:/downloads
      - ${DELUGE_CONFIG_LOCATION}:/config
    environment:
      - PUID=${DELUGE_USER_ID}
      - PGID=${DELUGE_GROUP_ID}
      - TZ=Europe/Brussels
  # Movie auto-search and download
  radarr:
    image: lscr.io/linuxserver/radarr:6.0.4.10291-ls289
    restart: unless-stopped
    environment:
      - PUID=${RADARR_USER_ID}
      - PGID=${RADARR_GROUP_ID}
      - TZ=Europe/Brussels
    volumes:
      - ${RADARR_CONFIG_LOCATION}:/config
      - ${RADARR_MOVIES_LOCATION}:/movies
      - ${RADARR_DOWNLOADS_LOCATION}:/downloads
  # TV auto-search and download
  sonarr:
    image: lscr.io/linuxserver/sonarr:4.0.16.2944-ls300
    restart: unless-stopped
    environment:
      - PUID=${SONARR_USER_ID}
      - PGID=${SONARR_GROUP_ID}
      - TZ=Europe/Brussels
    volumes:
      - ${SONARR_CONFIG_LOCATION}:/config
      - ${SONARR_TV_LOCATION}:/tv
      - ${SONARR_DOWNLOADS_LOCATION}:/downloads
  # Radarr and Sonarr config managment
  profilarr:
      image: santiagosayshey/profilarr:v1.1.3
      restart: unless-stopped
      volumes:
        - ${PROFILARR_CONFIG_LOCATION}:/config
      environment:
        - PUID=${PROFILARR_USER_ID}
        - PGID=${PROFILARR_GROUP_ID}
        - TZ=Europe/Brussels
  # Torrent indexer
  prowlarr:
    image: linuxserver/prowlarr:2.3.0.5236-ls134
    restart: unless-stopped
    volumes:
      - ${PROWLARR_CONFIG_LOCATION}:/config
    environment:
      - PUID=${PROWLARR_USER_ID}
      - PGID=${PROWLARR_GROUP_ID}
      - TZ=Europe/Brussels
  # Cloudflare bypass
  flaresolverr:
    image: flaresolverr/flaresolverr:latest
    restart: unless-stopped
    environment:
      - TZ=Europe/Brussels
  # Media server
  jellyfin:
    image: jellyfin/jellyfin:10.11.5
    restart: unless-stopped
    user: ${JELLYFIN_USER_ID}:${JELLYFIN_GROUP_ID}
    volumes:
      - ${JELLYFIN_CONFIG_LOCATION}:/config
      - ${JELLYFIN_CACHE_LOCATION}:/cache
      - ${JELLYFIN_MEDIA_LOCATION_MOVIES_1}:/movies1:ro
      - ${JELLYFIN_MEDIA_LOCATION_TV_1}:/tv1:ro